from django import forms


class DataForm(forms.Form):
    age = forms.IntegerField(label="AGE")
    bmi = forms.FloatField(label="BMI")
    appid = forms.CharField(label="APPID", max_length=100)
    sex = forms.ChoiceField(label="SEX", choices=[('M', 'Male'), ('F', 'Female')])
    wrist = forms.FloatField(label="WRIST")
    migration_address = forms.CharField(label="MIGRATION ADDRESS", max_length=255)
    height = forms.FloatField(label="HEIGHT")
    waist = forms.FloatField(label="WAIST")
    current_address = forms.CharField(label="CURRENT ADDRESS", max_length=255)
    hip = forms.FloatField(label="HIP")
    weight = forms.FloatField(label="WEIGHT")
    body_frame = forms.CharField(label="शरीरिक संगठन(Body Frame)?", max_length=100)
    body_bulk = forms.CharField(label="शरीर संहनन(Body Bulk)?", max_length=100)
    musculature = forms.CharField(label="शारीरिक संहनन (मांसपेशीय)Body Build (Musculature)?", max_length=100)
    forehead_length = forms.FloatField(label="माथे की लंबाई(Forehead Length)?")
    nails_texture = forms.CharField(label="नाखून बनावट(Nails Texture)?", max_length=100)
    nails_colour = forms.CharField(label="नाखुनो का रंग(Nails Colour)?", max_length=100)
    fingernail_size = forms.CharField(label="उंगली के नाखुन का आकार(Finger Nail Size)?", max_length=100)
    skin_appearance = forms.CharField(label="त्वचा की उपस्थिति(Skin Appearance)?", max_length=100)
    skin_colour = forms.CharField(label="त्वचा का रंग/आभा(Skin Colour/Complexion)?", max_length=100)
    skin_nature = forms.CharField(label="त्वचा की प्रकृति(Skin Nature)?", max_length=100)
    skin_texture = forms.CharField(label="त्वचा की बनावट(Skin Texture)?", max_length=100)
    hair_texture = forms.CharField(label="बालों की बनावट(Hair Texture), बालों की प्रकृति(Hair Nature)?", max_length=100)
    hair_nature = forms.CharField(label="बालों की प्रकृति(Hair Nature)?", max_length=100)
    observe_condition = forms.CharField(label="क्या आप देखते हैं कि आपके पास है?(Do you observe you have?)?", max_length=100)
    appetite = forms.CharField(label="आपकी भूख कैसी है?(नियमितता)(How is your appetite?(Regularity, Frequency, Amount))?", max_length=100)
    taste_preference = forms.CharField(label="स्वाद वरीयता(Taste Preference)?", max_length=100)
    digestibility = forms.CharField(label="क्या आप अपने द्वारा खाए गए भोजन की मात्रा को पचा पा रहे हैं?(Are you able to digest the amount of food consumed by you?)", max_length=100)
    fat_food_preference = forms.CharField(label="क्या आप वसा से भरपूर भोजन लेना पसंद करते हैं जैसे(Do you prefer to take food rich in fats like)?", max_length=100)
    body_temperature = forms.CharField(label="क्या आपके शरीर का तापमान सामान्य रहता है?(Does your body temperature in general remains ?)", max_length=100)
    perspiration = forms.CharField(label="आपके पसीने के बारे में कैसे है?(How about your Perspiration?)", max_length=100)
    sleep = forms.CharField(label="आपकी नींद कैसी है?(राशि)(How about your sleep ?(amount))", max_length=100)
    sleep_immediately = forms.CharField(label="क्या आपको बिस्तर पर जाने के तुरंत बाद नींद आती है?(Do you get sleep immediately after going to bed ?)", max_length=100)
    sleep_quality = forms.CharField(label="नींद की गुणवत्ता(Quality of Sleep)?", max_length=100)
    bowel_habits = forms.CharField(label="आपकी शौच प्रवृत्तीआदतों के बारे में कैसे है ?(How about your bowel habits?)", max_length=100)
    stool_preference = forms.CharField(label="शौच के प्रति आपकी प्रवृत्ती केसी है? (अधिकतर)(Do you tend to have ?)", max_length=100)
    stool_consistency = forms.CharField(label="मल प्रवृत्ती कैसी होती है अधिकतर(Stool Consistency)?", max_length=100)
    body_weight_change = forms.CharField(label="आपके शरीर के वजन में परिवर्तन के बारे में आप कैसे?(How about changes in your body weight ?)", max_length=100)
    body_odour = forms.CharField(label="क्या आपके शरीर से दुर्गंध आती है?(Do you have body odor ?)", max_length=100)
    weather_preference = forms.CharField(label="आप कौन सा मौसम पसंद करते हैं?(Which weather do you prefer ?)", max_length=100)
    health_in_weather = forms.CharField(label="आपको किस मौसम में स्वास्थ्य समस्याएं होती हैं?(In which weather do you have health problems ?)", max_length=100)
    illness_frequency = forms.CharField(label="आप कितनी बार बीमार पड़ते हैं?(How frequently do you fall ill?)", max_length=100)
    recovery = forms.CharField(label="यदि आप बीमार पड़ते हैं तो क्या आप आसानी से ठीक हो जाते हैं?(If you fall ill do you get cured easily?)", max_length=100)
    speaking_amount = forms.CharField(label="बोलने की मात्रा(Amount of speaking)?", max_length=100)
    voice_quality = forms.CharField(label="आवाज की गुणवत्ता(Quality of voice)?", max_length=100)
    speaking_speed = forms.CharField(label="बोलने की गति/शैली(Speed/Style of Speaking)?", max_length=100)
    movements = forms.CharField(label="स्वैच्छिक और अनैच्छिक गतियां(Voluntary and Involuntary Movements)?- हाथ की गति(Hand), टाँगों की गति(Leg), आइब्रो मूवमेंट(Eyebrow), कंधे की गति(Shoulder)-समग्र आंदोलन(Overall)", max_length=100)
    mental_strength = forms.CharField(label="मानसिक शक्ति(Mental Strength)?", max_length=100)
    tiredness = forms.CharField(label="आप कितनी बार थकान महसूस करते हैं?(How frequently you feel tired?)", max_length=100)
    memorization_speed = forms.CharField(label="आप कितनी जल्दी चीजों को याद कर सकते हैं?(How quickly you can memorize things?)", max_length=100)
    forgetfulness = forms.CharField(label="आप कितने भुलक्कड़ हैं?(How forgetful you are?)", max_length=100)
    memory_retention = forms.CharField(label="आपकी मेमोरी रिटेंशन पावर कैसी है?(How is your memory retention power?)", max_length=100)
    is_you = forms.CharField(label="क्या आप है एक…(Are you a…)?", max_length=100)
    preference = forms.CharField(label="क्या आपको पसंद है?(Do you like to ?)", max_length=100)
    doctor_prakriti = forms.CharField(label="DOCTOR_Prakriti", max_length=100)
    kapha = forms.CharField(label="Kapha", max_length=100)
    pitta = forms.CharField(label="Pitta", max_length=100)
    vata = forms.CharField(label="Vata", max_length=100)
    note = forms.CharField(label="NOTE", max_length=255)
    app_prakarti = forms.CharField(label="APP_Prakarti", max_length=100)
